

FROM golang:1.25.6-alpine AS builder
WORKDIR /app
 COPY go.mod go.sum ./ 
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /app/multi-service .

FROM alpine:latest
COPY --from=builder /app/multi-service /multi-service
RUN chmod +x /multi-service
EXPOSE 3000
ENTRYPOINT ["/multi-service"]
